# YOUR CODE HERE
import sys

# Read the input string from standard input
s = sys.stdin.readline().strip()

# Split the string by the '.' character
# This creates a list of substrings. For example, "a.b.c" becomes ['a', 'b', 'c'].
# If the string starts with '.', the first element will be empty, e.g., ".z" becomes ['', 'z'].
# If there are consecutive '.', empty strings will be included, e.g., "a..b" becomes ['a', '', 'b'].
parts = s.split('.')

# The problem asks for the last substring after splitting by '.'.
# This corresponds to the last element of the list generated by split().
# Since the problem guarantees S does not end with '.', the last element
# will always be the desired suffix.
last_part = parts[-1]

# Print the result to standard output
print(last_part)