ps[x][y][z] = A[x][y][z]
                  + ps[x-1][y][z]
                  + ps[x][y-1][z]
                  + ps[x][y][z-1]
                  - ps[x-1][y-1][z]
                  - ps[x-1][y][z-1]
                  - ps[x][y-1][z-1]
                  + ps[x-1][y-1][z-1]