def main():
    import sys
    # Read the generated string from standard input
    S = sys.stdin.readline().strip()
    
    # The string S is generated by:
    # | + (A1 copies of '-') + | + (A2 copies of '-') + | ... + (AN copies of '-') + |
    # Splitting by the '|' character gives: ['', (A1 dashes), (A2 dashes), ..., (AN dashes), '']
    # We ignore the first and last empty strings.
    segments = S.split('|')[1:-1]

    # The length of each segment is equal to the corresponding A_i.
    A = [str(len(segment)) for segment in segments]
    
    # Print the sequence of A_i separated by spaces.
    print(" ".join(A))

if __name__ == '__main__':
    main()